# Generated by Django 3.0.5 on 2020-11-16 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website2', '0002_auto_20201116_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='posti',
            new_name='post',
        ),
    ]
