# Generated by Django 3.0.3 on 2020-12-01 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website2', '0003_auto_20201116_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
