# Generated by Django 3.0.3 on 2020-12-01 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website2', '0005_home'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='image',
            new_name='imaging',
        ),
    ]
