# Generated by Django 3.0.3 on 2020-12-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website2', '0009_auto_20201227_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpage',
            name='seo_des',
            field=models.TextField(blank=True, null=True),
        ),
    ]
