# Generated by Django 3.0.3 on 2020-12-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website2', '0010_auto_20201227_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpage',
            name='seo_des',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
