# Generated by Django 3.0.3 on 2020-12-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website2', '0011_auto_20201227_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpage',
            name='seo_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
