# Generated by Django 3.0.3 on 2020-12-27 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website2', '0012_postpage_seo_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postpage',
            name='seo_title',
        ),
    ]
