# Generated by Django 3.0.3 on 2021-01-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website2', '0014_auto_20210105_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpage',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
