# Generated by Django 3.0.3 on 2021-01-07 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website2', '0015_auto_20210105_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
