# Generated by Django 3.0.3 on 2021-01-07 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website2', '0017_auto_20210107_1013'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
