# Generated by Django 3.0.3 on 2021-01-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website2', '0018_delete_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
