# Generated by Django 3.0.3 on 2021-01-19 08:48

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website2', '0019_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpage',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
