# Generated by Django 3.0.3 on 2021-01-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website2', '0020_auto_20210119_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpage',
            name='seo_keywords',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
